import 'package:demoflu/demoflu.dart';

class GetStartedPage extends DemoFluPage {
  GetStartedPage() {
    textSection('Welcome to DemoFlu.');

    textSection()
      ..add('Allows you to create demonstrations by structuring')
      ..add(' them into pages and sections.');

    textSection()
      ..add('You can create various types of sections to convey different')
      ..add(' aspects of your package or widget. These sections include:');

    BulletsSection bullets = bulletsSection();
    bullets.create()
      ..add('Text: Provide explanatory text to guide users')
      ..add(' through your demonstration and explain key concepts.');
    bullets.create()
      ..add('Code Example: Showcase code snippets to illustrate')
      ..add(' how to use your package or widget in different scenarios.');
    bullets.create()
      ..add('Source Code: Display the complete source code of your')
      ..add(' demonstration for reference or further exploration.');
    bullets.create()
      ..add('Alerts: Highlight important information or')
      ..add(' warnings to ensure users are aware of critical details.');
    bullets.create()
      ..add('Console Output: Showcase the output of your code')
      ..add(' execution, displaying any print statements')
      ..add(' generated by the widget being tested');
    bullets.create()
      ..add('And more: Explore additional types of sections')
      ..add(' to further customize and enhance your demonstrations.');
  }

  //TODO divisor?
}
